Add SSR support for fluid layout
ampproject/amp-toolbox-php pull request #181
Opened 2021-05-04 21:08 UTC by westonruter

This is blocked by the AMP validator being updated, specifically to modify [`validateSsrLayout()`](https://github.com/ampproject/amphtml/blob/f2a49b8efa4ecb0cd1dd273977799299a9e1f816/validator/js/engine/validator.js#L4436-L4441) as follows:

```diff
      const validInternalClasses = Object.create(null);
      validInternalClasses[getLayoutClass(layout)] = 0;
      if (isLayoutSizeDefined(layout)) {
        // i-amphtml-layout-size-defined
        validInternalClasses[getLayoutSizeDefinedClass()] = 0;
      }
+     if ('fluid' === layout) {
+       validInternalClasses['i-amphtml-layout-awaiting-size'] = 0;
+     }
```

2021-06-04 21:12 UTC, westonruter commented
PHPUnit test to be resolved after https://github.com/ampproject/amp-toolbox/pull/1236 is merged and synced to this repo.

2021-06-04 21:27 UTC, westonruter commented
Let's try to get this included in AMP plugin v2.1.3.

2021-06-06 21:03 UTC, schlessera requested changes

2021-06-06 21:03 UTC, schlessera commented on src/Optimizer/Transformer/ServerSideRendering.php
> +                $styles .= 'width:100%;height:0;';
```suggestion
                $styles = 'width:100%;height:0;';
```

2021-06-07 00:07 UTC, schlessera approved these changes

2021-06-07 00:08 UTC, merged

2021-06-07 05:09 UTC, westonruter commented
See example of the fluid layout with SSR: https://amp-ad-with-fluid-layout.glitch.me/