Add HtmlEntities filter
ampproject/amp-toolbox-php pull request #452
Opened 2021-12-20 12:00 UTC by ediamin

This PR adds a new HtmlEntities filter which decode the html entities before it is loaded into the Dom\Document. Fixes #409

2021-12-20 15:26 UTC, schlessera requested changes

2021-12-21 13:08 UTC, schlessera requested changes

2021-12-21 13:36 UTC, ediamin commented on src/Dom/Document/Filter/NormalizeHtmlEntities.php
> +        }
Created an issue for the exception: https://github.com/ampproject/amp-toolbox-php/issues/454.

2022-01-04 15:16 UTC, schlessera commented on src/Dom/Document/Filter/NormalizeHtmlEntities.php
> +        }
The exception PR was merged, so this one can be updated now.

2022-01-05 05:37 UTC, ediamin commented on src/Dom/Document/Filter/NormalizeHtmlEntities.php
> +        }
Updated.

2022-01-05 14:31 UTC, schlessera requested changes

2022-01-05 14:32 UTC, schlessera approved these changes

2022-01-05 14:49 UTC, merged